camera:  
    camera_info_url: file://~/30530001390014h.yaml
    video_mode: format7_mode0
    brightness: 0
    gain: 122
    shutter: 2048
    framerate: 100
    trigger_mode: 0

processor:
    framerate_trigger: 100
    threshold_diff: 6
    threshold_clear: 0.3
    n_sigma: 7
    n_erode: 0
    roi:
        left: 0
        top: 0
        right: 1023
        bottom: 767
    dynamic_background: True
    use_cmp: False
    use_color_filter: False
    color_filter_1: 0
    color_filter_2: 150
    color_filter_3: 255
    color_filter_sat: 100
    visible_image_view: raw


